spring.application.name=jurosboleto

api.boleto=https://boleto.free.beeceptor.com/my/api/boleto

spring.datasource.url=jdbc:postgresql://localhost:5432/jurosboleto
spring.datasource.username=juros
spring.datasource.password=juros
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
